### ISSUE TITLE
Other players lanterns not emitting light in multiplayer (with shaders)

### ISSUE THREAD

**Issue by ACE1337x** [txnimc/ImmersiveLanterns#13]
Other players lanterns are not emitting light in multiplayer with shaders (Bliss) enabled, i've not checked without shaders yet though

**Comment by nthxny** [comment]
I'm not sure if this is possible because it's up to the shaders to determine if an entity should light up, and I can only realistically patch what Iris gives to the shaders. All this mod is doing to get handheld shader lighting working is tricking it into thinking the player is holding a lantern.

You can use Sodium Dynamic Lights and disable personal lighting, that way only other players would show up. that should work
